[package]
name = "tests"
version = "0.1.0"
edition = "2024"

[dependencies]
ckb-testtool = "1.0"
ckb-hash = "1.1"
obscell-v1-types = { path = "../contracts/obscell-v1-types" }
curve25519-dalek = { version = "4", default-features = false, features = ["alloc"] }
bulletproofs = { git = "https://github.com/zkcrypto/bulletproofs", rev = "04bce4e66013ff857ed462fd4206210544101461", default-features = false }
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ark-bn254 = "0.4"
ark-ec = "0.4"
ark-ff = "0.4"
ark-groth16 = "0.4"
ark-snark = "0.4"
