import '../env.js';
import express, { type Request, type Response, type NextFunction } from 'express';
import cors from 'cors';
import { loadRelayerConfig } from './config.js';
import { RelayerWallet } from './wallet.js';
import { submitRelay, type RelayRequest } from './relay.js';
import { fetchDepositRecoveryByCommitment, fetchFinalizedDepositNote, performLiveDeposit } from '../deposit/service.js';
import {
    CoordinatorHttpError,
    fetchCoordinatorDepositPools,
    fetchCoordinatorDepositSession,
    fetchLatestCoordinatorDepositPool,
} from '../coordinator/client.js';
import { logger } from '../utils/logger.js';
import { redis } from '../utils/redis.js';
import { initWaku, subscribeToWakuMessages, publishWakuMessage } from 'mixer-sdk';

import { rateLimit } from 'express-rate-limit';

const app = express();
app.set('trust proxy', 1);  

/**
 * Creates and returns the Relayer Express application.
 *
 * Endpoints:
 *   POST /relay         — Submit a ZK proof for the relayer to broadcast
 *   GET  /relay/:jobId  — Poll the status of a relay job
 *   GET  /health        — Relayer liveness + wallet balance
 *   GET  /info          — Public relayer metadata (fee rate, address)
 */
export function createRelayerApp() {
    const cfg = loadRelayerConfig();
    const wallet = new RelayerWallet(cfg);

    // Log the relayer balance on startup
    wallet.checkBalance().catch(err =>
        logger.warn('[Relayer] Could not check balance', { error: String(err) }),
    );

    const app = express();
    app.use(cors());
    app.use(express.json({ limit: '512kb' }));

    const apiLimiter = rateLimit({
        windowMs: 15 * 60 * 1000,
        max: 1000,
        message: { error: 'Too many requests, please try again later.' }
    });
    app.use('/relay', apiLimiter);

    app.post('/deposit', async (req: Request, res: Response, next: NextFunction) => {
        try {
            const walletAddress = typeof req.body?.walletAddress === 'string' ? req.body.walletAddress.trim() : '';
            const zkCommitment = typeof req.body?.zkCommitment === 'string' ? req.body.zkCommitment.trim() : '';
            const noteCreatedAt = Number.isFinite(req.body?.noteCreatedAt) ? Number(req.body.noteCreatedAt) : undefined;
            if (!walletAddress) {
                res.status(400).json({ error: 'walletAddress is required' });
                return;
            }
            if (!/^0x[0-9a-fA-F]{64}$/.test(zkCommitment)) {
                res.status(400).json({ error: 'zkCommitment must be a 32-byte hex string generated by the client' });
                return;
            }

            const result = await performLiveDeposit(walletAddress, { zkCommitment, noteCreatedAt });
            res.status(201).json(result);
        } catch (err) {
            next(err);
        }
    });

    app.get('/deposit/recovery/:zkCommitment', async (req: Request, res: Response, next: NextFunction) => {
        try {
            const zkCommitment = req.params.zkCommitment;
            if (!/^0x[0-9a-fA-F]{64}$/.test(zkCommitment)) {
                res.status(400).json({ error: 'zkCommitment must be a 32-byte hex string' });
                return;
            }

            const result = await fetchDepositRecoveryByCommitment(zkCommitment);
            res.json(result);
        } catch (err) {
            next(err);
        }
    });

    app.get('/deposit/pools/:poolId/participants/:participantId/note', async (req: Request, res: Response, next: NextFunction) => {
        try {
            const result = await fetchFinalizedDepositNote(req.params.poolId, req.params.participantId);
            res.json(result);
        } catch (err) {
            next(err);
        }
    });

    app.get('/deposit/session/:sessionId', async (req: Request, res: Response, next: NextFunction) => {
        try {
            const pool = await fetchCoordinatorDepositSession(req.params.sessionId);
            res.json(pool);
        } catch (err) {
            if (err instanceof CoordinatorHttpError && err.status === 404) {
                res.status(404).json({ error: err.message });
                return;
            }
            next(err);
        }
    });

    app.get('/deposit/pools', async (_req: Request, res: Response, next: NextFunction) => {
        try {
            const pools = await fetchCoordinatorDepositPools();
            res.json(pools);
        } catch (err) {
            next(err);
        }
    });

    app.get('/deposit/pools/latest/:denomination', async (req: Request, res: Response, next: NextFunction) => {
        try {
            const denomination = Number.parseInt(req.params.denomination, 10);
            if (!Number.isFinite(denomination)) {
                res.status(400).json({ error: 'Invalid denomination' });
                return;
            }

            const pool = await fetchLatestCoordinatorDepositPool(denomination);
            res.json(pool);
        } catch (err) {
            if (err instanceof CoordinatorHttpError && err.status === 404) {
                res.status(404).json({ error: err.message });
                return;
            }
            next(err);
        }
    });

    // ── POST /relay ────────────────────────────────────────────────────────────
    app.post('/relay', async (req: Request, res: Response, next: NextFunction) => {
        try {
            const body = req.body as RelayRequest;
            if (!body.nullifierHex || !body.transaction) {
                res.status(400).json({ error: 'Missing required fields: nullifierHex, transaction' });
                return;
            }

            const result = await submitRelay(body, wallet, cfg);
            res.status(202).json(result);
        } catch (err) {
            next(err);
        }
    });

    // ── GET /relay/:jobId ──────────────────────────────────────────────────────
    app.get('/relay/:jobId', async (req: Request, res: Response) => {
        const jobStr = await redis.get(`job:${req.params.jobId}`);
        if (!jobStr) {
            res.status(404).json({ error: 'Job not found' });
            return;
        }
        res.json(JSON.parse(jobStr));
    });

    // ── GET /health ────────────────────────────────────────────────────────────
    app.get('/health', async (_req: Request, res: Response) => {
        try {
            const balance = await wallet.getBalanceShannnons();
            let activeJobs = 0;
            if (redis.status === 'ready') {
                const jobKeys = await redis.keys('job:*');
                activeJobs = jobKeys.length;
            }
            res.json({
                status: 'ok',
                relayerAddress: wallet.getAddress(),
                balanceCKB: (Number(balance) / 1e8).toFixed(4),
                activeJobs,
                redis: redis.status === 'ready' ? 'connected' : 'fallback',
            });
        } catch {
            res.status(503).json({ status: 'degraded', reason: 'Cannot reach CKB node' });
        }
    });

    // ── GET /info ──────────────────────────────────────────────────────────────
    // Public metadata — the frontend reads this to show users the relayer's fee
    app.get('/info', (_req: Request, res: Response) => {
        res.json({
            relayerAddress: wallet.getAddress(),
            feeRate: cfg.feeRate,
            feePercent: `${(cfg.feeRate * 100).toFixed(2)}%`,
            network: process.env.CKB_NETWORK ?? 'testnet',
        });
    });

    // ── Error handler ──────────────────────────────────────────────────────────
    app.use((err: unknown, _req: Request, res: Response, _next: NextFunction) => {
        const message = err instanceof Error ? err.message : String(err);
        logger.error('[Relayer] Unhandled error', { error: message });
        res.status(500).json({ error: message });
    });

    return app;
}

/**
 * Start a Waku P2P listener for relay requests.
 *
 * This runs alongside the Express HTTP server. Users broadcast withdrawal
 * intents to the Waku network; the relayer picks them up, processes them,
 * and broadcasts the result back over Waku.
 *
 * This is the decentralized transport layer — no public endpoint required.
 */
export async function startWakuRelayListener() {
    const cfg = loadRelayerConfig();
    const wallet = new RelayerWallet(cfg);

    logger.info('[Relayer/Waku] Initializing Waku light node...');
    const waku = await initWaku();
    logger.info('[Relayer/Waku] Connected to Waku network. Listening for withdrawal_request messages.');

    await subscribeToWakuMessages(waku, 'withdrawal_request', async (payload: any) => {
        try {
            const request: RelayRequest = {
                nullifierHex: payload.nullifierHex,
                transaction: payload.transaction,
            };

            logger.info('[Relayer/Waku] Received withdrawal request via P2P', {
                nullifier: request.nullifierHex.slice(0, 18) + '...',
            });

            const result = await submitRelay(request, wallet, cfg);

            // Broadcast the result back over Waku so the user can track it
            await publishWakuMessage(waku, 'withdrawal_result', {
                jobId: result.jobId,
                status: result.status,
                txHash: result.txHash,
                nullifierHex: result.nullifierHex,
            });

            logger.info('[Relayer/Waku] Published withdrawal result', {
                jobId: result.jobId,
                status: result.status,
            });
        } catch (err) {
            logger.error('[Relayer/Waku] Failed to process withdrawal request', {
                error: String(err),
            });
        }
    });

    return waku;
}
