[target.riscv64imac-unknown-none-elf]
rustflags = [
    "-C",
    "target-feature=-a,-zaamo,-zalrsc",
]

[env]
CLANG = "riscv64-unknown-elf-gcc"
CC_riscv64imac_unknown_none_elf = "riscv64-unknown-elf-gcc"
AR_riscv64imac_unknown_none_elf = "riscv64-unknown-elf-ar"
CFLAGS_riscv64imac_unknown_none_elf = "-march=rv64imc -mabi=lp64"
